FROM node:20-alpine AS frontend_builder

WORKDIR /app

COPY ./Frontend/package*.json ./

RUN npm install

COPY ./Frontend .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY ./Backend/package*.json .

RUN npm install

COPY ./Backend .

COPY --from=frontend_builder /app/dist /app/public

CMD [ "node", "server.js" ]